# ⚠️ AUTO-GENERATED — REPLACE THIS FILE BEFORE FIRST BUILD
#
# This is a placeholder. NixOS generates the REAL hardware-configuration.nix
# with the actual disk layout, filesystem UUIDs, and kernel modules.
#
# Generate and copy it to this repo BEFORE your first nixos-rebuild:
#
#   nixos-generate-config --root /mnt
#   cp /mnt/etc/nixos/hardware-configuration.nix ~/config/nix/nixos/hardware-configuration.nix
#
# Or use disko (see disk-config.nix) before generating:
#   sudo nix run github:nix-community/disko -- --mode disko ./nix/nixos/disk-config.nix
#   sudo nixos-generate-config --root /mnt
{ ... }: {
  imports = [ ];
  # Replace with hardware-specific config generated by nixos-generate-config
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  fileSystems."/" = { device = "/dev/disk/by-label/root"; fsType = "btrfs"; };
  fileSystems."/boot" = { device = "/dev/disk/by-label/boot"; fsType = "vfat"; };
  swapDevices = [ { device = "/dev/disk/by-label/swap"; } ];
  nixpkgs.hostPlatform = "x86_64-linux";
}
